name: API Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Setup services
      run: make setup

    - name: Check service logs
      if: always()
      run: |
        docker-compose logs postgres > postgres.log
        docker-compose logs db-init > db-init.log
        docker-compose logs vault > vault.log
        docker-compose logs vault-init > vault-init.log
        docker-compose logs app > app.log
        echo "=== Postgres Logs ==="
        cat postgres.log
        echo "=== DB Init Logs ==="
        cat db-init.log
        echo "=== Vault Logs ==="
        cat vault.log
        echo "=== Vault Init Logs ==="
        cat vault-init.log
        echo "=== App Logs ==="
        cat app.log

    - name: Run tests
      run: make test-api 